import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Inter } from "next/font/google";
import "@/styles/globals.scss";
import { vvdsFifties } from "@/app/fonts/fonts";
import { Nav } from "@/components/layout/nav/nav";
import { Footer } from "@/components/layout/footer";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Moduref",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Home | Moduref</title>
      </head>

      <body
        className={`${inter.variable} ${vvdsFifties.variable} font-inter antialiased`}
      >
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}

// className="min-h-full flex flex-col"
